title: å‘¨åˆŠç¿»è¯‘è®¡åˆ’

name: FEDarling

email: im@daodaolee.cn

description: â›± å‘¨åˆŠç¿»è¯‘è®¡åˆ’ï¼Œç›®å‰æ¶‰åŠJavaScript Weeklyã€Mobile Dev Weeklyã€Frontend Focusã€React Statusã€Node Weekly å’Œ CSS WeeklyæœŸåˆŠï¼Œå¸Œæœ›è¯»è€…å¯ä»¥æœ‰æ‰€æ”¶è·ï¼ğŸ¥³
url: "https://fedarling.github.io"
baseurl: "/fe-translate-weekly"
repository: "FEDarling/fe-translate-weekly"
logo: "https://avatars.githubusercontent.com/u/97049302?s=400&u=9eeeeb9644d2ed3b862b8bab1a91adcf48792299&v=4"

words_per_minute: 200

social:
  name: DaoDaoLee
  links: https://github.com/daodaolee

author:
  name             : "FEDarling"
  avatar           : "https://avatars.githubusercontent.com/t/5522920?s=280&v=4"
  bio              : "Front End Darling Translate"
  location         : "China"
  email            : mailto:im@daodaolee.cn?cc=im@daodaolee.cn
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:im@daodaolee.cn?cc=im@daodaolee.cn
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: https://fedarling.github.io/fe-translate-weekly/
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/FEDarling/fe-translate-weekly

minimal_mistakes_skin: dark

# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - JavaScript_Weekly
  - CSS_Weekly
  - Mobile_Dev_Weekly
  - Frontend_Focus
  - React_Status
  - Node_Weekly

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FEDarling"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

search                   : true
search_full_content      : true
search_provider          : lunr

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true
  enable_coderay: false

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "JavaScript_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "CSS_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Mobile_Dev_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Frontend_Focus"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "React_Status"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Node_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
